# Generated by Django 3.0.3 on 2020-03-06 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_certificate_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='server',
            field=models.CharField(choices=[('QA', 'QA'), ('UAT', 'UAT')], default='QA', max_length=128),
        ),
    ]
