# Generated by Django 3.0.3 on 2020-03-10 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_certificate_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='file',
            field=models.ImageField(upload_to='media'),
        ),
    ]
