# Generated by Django 3.0.3 on 2020-03-11 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200310_1809'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='upload',
            options={'ordering': ['-id']},
        ),
    ]
